#include <mod/amlmod.h>
#include <mod/logger.h>
#include <timecyc.h>

uint8_t  CTimeCycle__m_nDirectionalMult[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nWaterFogAlpha[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nHighLightMinIntensity[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fCloudAlpha[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx2Alpha[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx2Blue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx2Green[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx2Red[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx1Alpha[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx1Blue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx1Green[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fPostFx1Red[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fWaterAlpha[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fWaterBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fWaterGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fWaterRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nFluffyCloudsBottomRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nFluffyCloudsBottomGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nFluffyCloudsBottomBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nLowCloudsBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nLowCloudsGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nLowCloudsRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fLightsOnGroundBrightness[NUMHOURS][NUMWEATHERS];
uint16_t CTimeCycle__m_fFogStart[NUMHOURS][NUMWEATHERS];
uint16_t CTimeCycle__m_fFarClip[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nPoleShadowStrength[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nLightShadowStrength[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nShadowStrength[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fSpriteBrightness[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fSpriteSize[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_fSunSize[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoronaBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoronaGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoronaRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoreBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoreGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSunCoreRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyBottomBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyBottomGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyBottomRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyTopBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyTopGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nSkyTopRed[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientBlue_Obj[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientGreen_Obj[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientRed_Obj[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientBlue[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientGreen[NUMHOURS][NUMWEATHERS];
uint8_t  CTimeCycle__m_nAmbientRed[NUMHOURS][NUMWEATHERS];

CColourSet m_CurrentColours;
CColourSet* m_ptrCurrentColours = &m_CurrentColours;